config/routes.rb
Rails.application.routes.draw do
  #resources :user_events, only: [:new, :create, :show] do 
#  	collection do 
#      get :event_users_details
#    end  
#  end
  root to: "events#index"
  resources :events, only: [:index] do
  	resources :user_events, only: [:index, :show, :new, :create] do
  		member do 
      	patch :cancel
    	end
  	end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events

  def valid_event?
    timing.in_time_zone('Kolkata') > Time.now.in_time_zone('Kolkata')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
  has_many :user_events

  def female?
    gender == 'Female'
  end
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
  enum status: { unattend: 0, attended: 1 }
  FEMALE_DISCOUNT = 5

  validate :multiple_registrations, on: :create
  validate :valid_event

  before_create do
    self.status = :attended
    if user.female?
      self.ticket_fee = ((100 - FEMALE_DISCOUNT) * event.ticket_fee) / 100
    end
  end

  def unattend
    update(status: :unattend)
  end

  def can_attend?
    unattend?
  end

  def can_unattend?
    attended?
  end

  def valid_event
    if event.timing.in_time_zone('Kolkata') < Time.now.in_time_zone('Kolkata')
      errors.add(:error, 'You cannot attend/unattend for past event')
    end
  end

  def multiple_registrations
    if event.user_events.where(user_id: user.id, status: :attended).exists?
      errors.add(:error, 'You cannot register for same event multiple times')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email) }
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name, :gender) }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  before_action :set_user_event, only: [:show, :cancel]

  def index
    if params[:event_id]
      @event = Event.find_by_id(params[:event_id])
      @event_users = UserEvent.includes(:user).where(event_id: params[:event_id], status: :attended)
      @user_event = UserEvent.where(event_id: params[:event_id], user_id: current_user.id).last if current_user
    end
  end

  def show
    render body: nil unless @user_event
  end

  def new
    @user_event = UserEvent.new
    @event = Event.find_by_id(params[:event_id])
  end

  def create
    @user_event = current_user.user_events.create(user_event_params)
    respond_to do |format|
      if @user_event.save
        format.html { redirect_to event_user_event_path(event_id: @user_event.event_id, id: @user_event.id), notice: 'You are successfully registered for event.' }
        format.json { render :show, status: :created, location: @user_event }
      else
        format.html { redirect_to event_user_events_path(event_id: @user_event.event_id), notice: @user_event.errors.messages[:error].join(',') }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel
    @user_event.unattend
    respond_to do |format|
      if @user_event.save
        format.html { redirect_to event_user_event_path(event_id: @user_event.event_id, id: @user_event.id), notice: 'You are successfully unregistered for event.' }
        format.json { head :no_content }
      else
        format.html { redirect_to event_user_events_path(event_id: @user_event.event_id), notice: @user_event.errors.messages[:error].join(',') }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user_event
    @user_event = current_user.user_events.find_by_id(params[:id])
  end

  def user_event_params
    params.permit(:event_id, :ticket_fee)
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

private

def sign_up_params
   params.require(:user).permit(:name,:gender,:email,:password,:password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ticket_fee %>
    <%= form.number_field :ticket_fee %>
  </div>

  <div class="field">
    <%= form.label :timing %>
    <%= form.datetime_select :timing %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ticket fee</th>
      <th>Timing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%=link_to event.name, event_user_events_path(:event_id => event.id) %></td>
        <td><%= event.ticket_fee %></td>
        <td><%= event.timing.in_time_zone('Kolkata').strftime("%d %b %Y %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/_header.erb
<main>
	<section class="row">
		<% if current_user.present? %>
			<div class='col-md-2' >
				<%= link_to "Home", events_path, :class => 'navbar-link'  %> | 
				<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			</div>
		<% else %>
			<div class='col-md-2' >
				<%= link_to "Home", events_path, :class => 'navbar-link'  %> | 
				<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
				<%= link_to "Register", new_user_registration_path, :class => 'navbar-link'  %> 
			</div>
		<% end %>
	</section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventsWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "layouts/header" %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/user_events/_form.html.erb
<%= form_with url: "/events/#{event.id}/user_events" do |form| %>
  <% if user_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_event.errors.count, "error") %> prohibited this user_event from being saved:</h2>

      <ul>
      <% user_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_name %>
    <%= form.label event.name, disabled: true %>
  </div>

  <div class="field">
    <%= form.hidden_field :event_id, value: event.id%>
  </div>

  <div class="field">
    <%= form.label :ticket_fee %>
    <%= form.label event.ticket_fee, disabled: true %>
  </div>

  <div class="field">
    <%= form.hidden_field :ticket_fee, value: event.ticket_fee%>
  </div>

  <div class="actions">
    <%= form.submit :Register%>
  </div>
<% end %>

app/views/user_events/edit.html.erb
<h1>Editing User Event</h1>

<%= render 'form', user_event: @user_event %>

<%= link_to 'Show', @user_event %> |
<%= link_to 'Back', user_events_path %>

app/views/user_events/event_users_details.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Participant Details</h1>

<%= link_to 'Attend', new_user_event_path(:event_id => @event.id) %>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_users.each do |user_event| %>
      <tr>
        <td><%= user_event.user.name %></td>
        <td><%= user_event.user.gender %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/user_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Users</h1>

<% if current_user %>
  <% if @event.valid_event? %>
    <% if @user_event.present? && @user_event.can_unattend?%>
      <%= link_to 'Unattend', event_user_event_path(event_id: @event.id, id: @user_event.id) %>
    <% elsif @user_event.nil? || @user_event.can_attend? %>
      <%= link_to 'Attend', new_event_user_event_path(:event_id => @event.id) %>
    <% end %>
  <% end %>
<% end %>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Ticket fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_users.each do |user_event| %>
      <tr>
        <td><%= user_event.user.name %></td>
        <td><%= user_event.user.gender %></td>
        <td><%= user_event.ticket_fee %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/user_events/new.html.erb
<h1>New User Event</h1>

<%= render 'form', user_event: @user_event, event: @event %>

<%= link_to 'Back', event_user_events_path %>

app/views/user_events/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_with(url: cancel_event_user_event_path, method: "patch") do |form| %>
  <% if @user_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_event.errors.count, "error") %> prohibited this @user_event from being saved:</h2>

      <ul>
      <% @user_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event %>
    <%= form.label @user_event.event.name, disabled: true%> 
  </div>

  <div class="field">
    <%= form.label :ticket_fee %>
    <%= form.label @user_event.ticket_fee, disabled: true%> 
  </div>

  <div class="field">
    <%= form.hidden_field :id, value: @user_event.id%>
  </div>

  <%if @user_event.present? && @user_event.can_unattend?%>
    <div class="actions">
      <%= form.submit 'Unattend'%>
    </div>
  <% end %>
<% end %>